version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: git submodule update --init --recursive
build:
  project: BaluScript.sln
  verbosity: minimal
test_script:
- cmd: vstest.console.exe /logger:Appveyor Output/Debug/Test.dll