
BALU_SCRIPT_OPCODE_BEGIN(Enum)
{
	BALU_SCRIPT_OPCODE_ELEM(NONE),
	
	BALU_SCRIPT_OPCODE_ELEM(EQUAL),	
	BALU_SCRIPT_OPCODE_ELEM(NOT_EQUAL),

	//int 
	BALU_SCRIPT_OPCODE_ELEM(INT_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM(INT_PLUS),
	BALU_SCRIPT_OPCODE_ELEM(INT_MINUS),
	BALU_SCRIPT_OPCODE_ELEM(INT_DIV),
	BALU_SCRIPT_OPCODE_ELEM(INT_MUL),
	BALU_SCRIPT_OPCODE_ELEM(INT_MOD),

	BALU_SCRIPT_OPCODE_ELEM(INT_UNARY_MINUS),
	BALU_SCRIPT_OPCODE_ELEM(R_INT_UNARY_MINUS),

	BALU_SCRIPT_OPCODE_ELEM(INT_PREFIX_INC),
	BALU_SCRIPT_OPCODE_ELEM(INT_PREFIX_DEC),

	BALU_SCRIPT_OPCODE_ELEM(INT_PLUS_A),
	BALU_SCRIPT_OPCODE_ELEM(INT_MINUS_A),
	BALU_SCRIPT_OPCODE_ELEM(INT_MUL_A),
	BALU_SCRIPT_OPCODE_ELEM(INT_DIV_A),
	BALU_SCRIPT_OPCODE_ELEM(INT_MOD_A),

	BALU_SCRIPT_OPCODE_ELEM(INT_LESS),
	BALU_SCRIPT_OPCODE_ELEM(INT_LESS_EQ),
	BALU_SCRIPT_OPCODE_ELEM(INT_GREATER),
	BALU_SCRIPT_OPCODE_ELEM(INT_GREATER_EQ),

	BALU_SCRIPT_OPCODE_ELEM(INT_TO_FLOAT),
	BALU_SCRIPT_OPCODE_ELEM(R_INT_TO_FLOAT),
	BALU_SCRIPT_OPCODE_ELEM(INT_TO_BOOL),
	BALU_SCRIPT_OPCODE_ELEM(R_INT_TO_BOOL),
	BALU_SCRIPT_OPCODE_ELEM(INT_TO_VEC2),
	BALU_SCRIPT_OPCODE_ELEM(INT_TO_VEC2I),

	//int math
	BALU_SCRIPT_OPCODE_ELEM(INT_ABS),
	BALU_SCRIPT_OPCODE_ELEM(INT_MAXIMUM),
	BALU_SCRIPT_OPCODE_ELEM(INT_MINIMUM),
	BALU_SCRIPT_OPCODE_ELEM(INT_SIGN),


	//float
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_PRINT),

	BALU_SCRIPT_OPCODE_ELEM(FLOAT_PLUS),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_MINUS),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_DIV),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_MULT),

	BALU_SCRIPT_OPCODE_ELEM(FLOAT_UNARY_MINUS),
	BALU_SCRIPT_OPCODE_ELEM(R_FLOAT_UNARY_MINUS),

	BALU_SCRIPT_OPCODE_ELEM(FLOAT_PLUS_A),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_MINUS_A),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_MUL_A),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_DIV_A),

	BALU_SCRIPT_OPCODE_ELEM(FLOAT_LESS),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_LESS_EQ),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_GREATER),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_GREATER_EQ),

	BALU_SCRIPT_OPCODE_ELEM(FLOAT_TO_BOOL),
	BALU_SCRIPT_OPCODE_ELEM(R_FLOAT_TO_BOOL),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_TO_INT),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_TO_VEC2),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_TO_VEC2I),

	//float math
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_ABS),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_ASIN),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_ACOS),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_ATAN),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_CEIL),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_CLAMP),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_COS),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_DEG_TO_RAD),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_EXP),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_FLOOR),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_FRAC),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_LOG),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_LOG2),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_LOG10),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_MAX),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_MIN),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_PI),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_POW),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_RAD_TO_DEG),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_RAND),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_SIGN),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_SIN),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_SQRT),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_SQR),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_TAN),
	BALU_SCRIPT_OPCODE_ELEM(FLOAT_TRUNC),

	//bool
	BALU_SCRIPT_OPCODE_ELEM(BOOL_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM(BOOL_AND),
	BALU_SCRIPT_OPCODE_ELEM(BOOL_OR),
	BALU_SCRIPT_OPCODE_ELEM(BOOL_NOT),

	//vec2
	BALU_SCRIPT_OPCODE_ELEM(VEC2_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_PLUS_A),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_MINUS_A),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_MUL_A),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_DIV_A),

	BALU_SCRIPT_OPCODE_ELEM(VEC2_PLUS),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_MINUS),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_MULT),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_DIV),

	BALU_SCRIPT_OPCODE_ELEM(VEC2_UNARY_MINUS),
	BALU_SCRIPT_OPCODE_ELEM(R_VEC2_UNARY_MINUS),

	BALU_SCRIPT_OPCODE_ELEM(RV_VEC2_GET_ELEMENT),
	BALU_SCRIPT_OPCODE_ELEM(VV_VEC2_GET_ELEMENT),

	BALU_SCRIPT_OPCODE_ELEM(VEC2_DISTANCE),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_DOT),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_LENGTH),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_NORMALIZE),
	BALU_SCRIPT_OPCODE_ELEM(VEC2_REFLECT),

	//vec2i
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_PLUS_A),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_MINUS_A),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_MUL_A),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_DIV_A),

	BALU_SCRIPT_OPCODE_ELEM(VEC2I_PLUS),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_MINUS),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_MULT),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_DIV),

	BALU_SCRIPT_OPCODE_ELEM(VEC2I_UNARY_MINUS),
	BALU_SCRIPT_OPCODE_ELEM(R_VEC2I_UNARY_MINUS),

	BALU_SCRIPT_OPCODE_ELEM(RV_VEC2I_GET_ELEMENT),
	BALU_SCRIPT_OPCODE_ELEM(VV_VEC2I_GET_ELEMENT),

	BALU_SCRIPT_OPCODE_ELEM(VEC2I_DISTANCE),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_DOT),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_LENGTH),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_NORMALIZE),
	BALU_SCRIPT_OPCODE_ELEM(VEC2I_REFLECT),

	BALU_SCRIPT_OPCODE_ELEM(OP_END)
};
