
BALU_SCRIPT_OPCODE_BEGIN(Enum)
{
	BALU_SCRIPT_OPCODE_ELEM0(NONE),

	//braching
	BALU_SCRIPT_OPCODE_ELEM2(LABEL,		1/*label index*/,0),
	BALU_SCRIPT_OPCODE_ELEM2(GOTRUE,	1/*target label*/,0),
	BALU_SCRIPT_OPCODE_ELEM2(GOFALSE,	1/*target label*/,0),
	BALU_SCRIPT_OPCODE_ELEM2(GOTO,		1/*target label*/,0),

	//runtime checks
	BALU_SCRIPT_OPCODE_ELEM0(METHOD_HAS_NOT_RETURN_A_VALUE),

	// помещение в стек значений, ссылок и т.д.
	BALU_SCRIPT_OPCODE_ELEM2(PUSH_GLOBAL_REF,		1/*global var offset*/,0),
	BALU_SCRIPT_OPCODE_ELEM2(GLOBAL_TESTANDSET,		1/*global_offset*/,1/*gofalse_label*/),	//проверяет значение в глобальной переменной и если оно ноль то устанавливает в 1, иначе переход
	BALU_SCRIPT_OPCODE_ELEM2(PUSH_LOCAL_REF,		1/*local_var_offset*/,0),		// помещение ссылки на локальную переменную в стек  *sp=(local_var_offset+stack_top)
	BALU_SCRIPT_OPCODE_ELEM2(PUSH_LOCAL_REF_COPY,	1/*local_var_offset*/,0),		// используется для копирования ссылки параметра по адресу val на вершину
	BALU_SCRIPT_OPCODE_ELEM2(PUSH_MEMBER_REF,		1/*member offset*/,0),			// (member_offset+this_pointer)
	BALU_SCRIPT_OPCODE_ELEM0(PUSH_THIS),
	BALU_SCRIPT_OPCODE_ELEM2(PUSH_STRING_CONST,		1/*string id*/,0),
	BALU_SCRIPT_OPCODE_ELEM2(PUSH,					1/*val*/,0),
	BALU_SCRIPT_OPCODE_ELEM2(PUSH_COUNT,			1/*count*/,0),
	BALU_SCRIPT_OPCODE_ELEM2(PUSH_STACK_HIGH_REF,	1/*object_size*/,0),			//поместить в стек (sp-val1)
	BALU_SCRIPT_OPCODE_ELEM2(ADD_OFFSET,			1/*offset*/,0),				//прибавить смещение к ссылке на вершине стека
	//
	BALU_SCRIPT_OPCODE_ELEM2(POP_COUNT,		1/*count*/,0),	
	BALU_SCRIPT_OPCODE_ELEM2(RVALUE,		1/*operand_size*/,1/*copy_constr*/),	
	BALU_SCRIPT_OPCODE_ELEM2(GET_MEMBER,	1/*copy_constr*/,1/*destr*/),

	//
	BALU_SCRIPT_OPCODE_ELEM4(ASSIGN,	1/*right_ref*/,0, 1/*operand_size*/,0),		
	BALU_SCRIPT_OPCODE_ELEM4(EQUAL,		1,1, 1/*operand_size*/,0),	
	BALU_SCRIPT_OPCODE_ELEM4(NOT_EQUAL,	1,1, 1/*operand_size*/,0),
	//

	//func

	BALU_SCRIPT_OPCODE_ELEM2(CALL_METHOD,	1/*method_id*/,0),	
	BALU_SCRIPT_OPCODE_ELEM2(RETURN,		1/*locals_params_size*/,1/*return_val_size*/),	

	//static array

	BALU_SCRIPT_OPCODE_ELEM0(RV_STATIC_ARR_GET_ELEMENT),
	BALU_SCRIPT_OPCODE_ELEM2(R_STATIC_ARR_DEF_CONSTR,	1/*methods_id*/,0),
	BALU_SCRIPT_OPCODE_ELEM0(RR_STATIC_ARR_COPY_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM0(R_STATIC_ARR_DESTR),
	BALU_SCRIPT_OPCODE_ELEM4(STATIC_ARR_ASSIGN,		1,0, 1/*size*/,0),
	BALU_SCRIPT_OPCODE_ELEM4(STATIC_ARR_EQUAL,		1,1, 1/*size*/,0),

	//dynamic array

	BALU_SCRIPT_OPCODE_ELEM2(R_DYN_ARR_DEF_CONSTR,	1/*methods_id*/,0),
	BALU_SCRIPT_OPCODE_ELEM0(RR_DYN_ARR_COPY_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM0(R_DYN_ARR_DESTR),
	BALU_SCRIPT_OPCODE_ELEM0(RV_DYN_ARR_GET_ELEMENT),
	BALU_SCRIPT_OPCODE_ELEM4(DYN_ARR_ASSIGN,	1,0, 0,0),
	BALU_SCRIPT_OPCODE_ELEM4(DYN_ARR_EQUAL,		1,1, 0,0),
	BALU_SCRIPT_OPCODE_ELEM0(RV_DYN_ARR_SET_HIGH),
	BALU_SCRIPT_OPCODE_ELEM0(R_DYN_ARR_GET_HIGH),

	//string

	BALU_SCRIPT_OPCODE_ELEM0(R_STRING_DEF_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM0(RR_STRING_COPY_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM0(R_STRING_DESTR),
	BALU_SCRIPT_OPCODE_ELEM4(STRING_ASSIGN,	1,0, 0,0),
	BALU_SCRIPT_OPCODE_ELEM4(STRING_EQUAL,	1,1, 0,0),
	BALU_SCRIPT_OPCODE_ELEM0(VV_STRING_PLUS),
	BALU_SCRIPT_OPCODE_ELEM0(RV_STRING_PLUS_ASSIGN),	
	BALU_SCRIPT_OPCODE_ELEM0(R_STRING_PRINT),
	BALU_SCRIPT_OPCODE_ELEM0(V_STRING_PRINT),


	//////////////////////////////////////////////////////////////////
	///////////////// Классы

	//int 
	BALU_SCRIPT_OPCODE_ELEM0(INT_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM0(INT_PLUS),
	BALU_SCRIPT_OPCODE_ELEM0(INT_MINUS),
	BALU_SCRIPT_OPCODE_ELEM0(INT_DIV),
	BALU_SCRIPT_OPCODE_ELEM0(INT_MUL),
	BALU_SCRIPT_OPCODE_ELEM0(INT_MOD),

	BALU_SCRIPT_OPCODE_ELEM0(INT_UNARY_MINUS),
	BALU_SCRIPT_OPCODE_ELEM0(R_INT_UNARY_MINUS),

	BALU_SCRIPT_OPCODE_ELEM0(INT_PLUS_A),
	BALU_SCRIPT_OPCODE_ELEM0(INT_MINUS_A),
	BALU_SCRIPT_OPCODE_ELEM0(INT_MUL_A),
	BALU_SCRIPT_OPCODE_ELEM0(INT_DIV_A),
	BALU_SCRIPT_OPCODE_ELEM0(INT_MOD_A),

	BALU_SCRIPT_OPCODE_ELEM0(INT_LESS),
	BALU_SCRIPT_OPCODE_ELEM0(INT_LESS_EQ),
	BALU_SCRIPT_OPCODE_ELEM0(INT_GREATER),
	BALU_SCRIPT_OPCODE_ELEM0(INT_GREATER_EQ),

	BALU_SCRIPT_OPCODE_ELEM0(INT_TO_FLOAT),
	BALU_SCRIPT_OPCODE_ELEM0(R_INT_TO_FLOAT),
	BALU_SCRIPT_OPCODE_ELEM0(INT_TO_BOOL),
	BALU_SCRIPT_OPCODE_ELEM0(R_INT_TO_BOOL),
	BALU_SCRIPT_OPCODE_ELEM0(INT_TO_VEC2),

	//int math
	BALU_SCRIPT_OPCODE_ELEM0(INT_ABS),
	BALU_SCRIPT_OPCODE_ELEM0(INT_MAXIMUM),
	BALU_SCRIPT_OPCODE_ELEM0(INT_MINIMUM),
	BALU_SCRIPT_OPCODE_ELEM0(INT_SIGN),


	//float
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_PRINT),

	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_PLUS),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_MINUS),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_DIV),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_MULT),

	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_UNARY_MINUS),
	BALU_SCRIPT_OPCODE_ELEM0(R_FLOAT_UNARY_MINUS),

	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_PLUS_A),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_MINUS_A),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_MUL_A),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_DIV_A),

	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_LESS),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_LESS_EQ),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_GREATER),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_GREATER_EQ),

	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_TO_BOOL),
	BALU_SCRIPT_OPCODE_ELEM0(R_FLOAT_TO_BOOL),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_TO_INT),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_TO_VEC2),

	//float math
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_ABS),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_ASIN),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_ACOS),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_ATAN),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_CEIL),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_CLAMP),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_COS),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_DEG_TO_RAD),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_EXP),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_FLOOR),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_FRAC),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_LOG),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_LOG2),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_LOG10),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_MAX),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_MIN),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_PI),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_POW),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_RAD_TO_DEG),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_RAND),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_SIGN),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_SIN),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_SQRT),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_SQR),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_TAN),
	BALU_SCRIPT_OPCODE_ELEM0(FLOAT_TRUNC),

	//bool
	BALU_SCRIPT_OPCODE_ELEM0(BOOL_CONSTR),
	BALU_SCRIPT_OPCODE_ELEM0(BOOL_AND),
	BALU_SCRIPT_OPCODE_ELEM0(BOOL_OR),
	BALU_SCRIPT_OPCODE_ELEM0(BOOL_NOT),

	//vec2
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_PLUS_A),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_MINUS_A),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_MUL_A),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_DIV_A),

	BALU_SCRIPT_OPCODE_ELEM0(VEC2_PLUS),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_MINUS),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_MULT),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_DIV),

	BALU_SCRIPT_OPCODE_ELEM0(VEC2_UNARY_MINUS),
	BALU_SCRIPT_OPCODE_ELEM0(R_VEC2_UNARY_MINUS),

	BALU_SCRIPT_OPCODE_ELEM0(RV_VEC2_GET_ELEMENT),
	BALU_SCRIPT_OPCODE_ELEM0(VV_VEC2_GET_ELEMENT),

	BALU_SCRIPT_OPCODE_ELEM0(VEC2_CROSS),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_DISTANCE),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_DOT),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_LENGTH),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_NORMALIZE),
	BALU_SCRIPT_OPCODE_ELEM0(VEC2_REFLECT),

	BALU_SCRIPT_OPCODE_ELEM0(OP_END)
}BALU_SCRIPT_OPCODE_END()
